kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./contracts/node_modules
      - ./js/client_js/node_modules
      - ./js/explorer/node_modules
      - ./js/franklin_lib/node_modules
      - ./target

- name: init
  image: matterlabs/ci
  commands:
  - export FRANKLIN_HOME=`pwd`
  - export PATH=$FRANKLIN_HOME/bin:$PATH
  - franklin env ci
  - franklin yarn
  - franklin db-wait
  depends_on:
    - restore-cache
   

- name: build-contracts
  image: matterlabs/ci
  commands:
  - export FRANKLIN_HOME=`pwd`
  - export PATH=$FRANKLIN_HOME/bin:$PATH
  - franklin build-contracts
  depends_on:
    - init

- name: rust-checks
  image: matterlabs/ci
  commands:
  - export FRANKLIN_HOME=`pwd`
  - export PATH=$FRANKLIN_HOME/bin:$PATH
  - export CARGO_HOME=$FRANKLIN_HOME/target/cargo
  - cargo fmt --all -- --check
  - cargo check
  depends_on:
    - build-contracts

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./contracts/node_modules
      - ./js/client_js/node_modules
      - ./js/explorer/node_modules
      - ./js/franklin_lib/node_modules
      - ./target

volumes:
  - name: cache
    host:
      path: /tmp/cache

services:
  - name: geth
    image: gluk64/franklin:geth
  - name: postgres
    image: postgres:10.4

trigger:
  event:
  - pull_request
