kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./contracts/node_modules
      - ./js/client_js/node_modules
      - ./js/explorer/node_modules
      - ./js/franklin_lib/node_modules

- name: yarn init
  image: node:10.16.3
  commands:
  - export FRANKLIN_HOME=`pwd`
  - export PATH=$FRANKLIN_HOME/bin:$PATH
  - franklin yarn

- name: build contracts
  image: node:10.16.3
  commands:
  - export FRANKLIN_HOME=`pwd`
  - export PATH=$FRANKLIN_HOME/bin:$PATH
  - franklin build-contracts

- name: rust check
  image: rust
  commands:
  - export FRANKLIN_HOME=`pwd`
  - export PATH=$FRANKLIN_HOME/bin:$PATH
  - export CARGO_HOME=$FRANKLIN_HOME/target/cargo
  - cargo check

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./contracts/node_modules
      - ./js/client_js/node_modules
      - ./js/explorer/node_modules
      - ./js/franklin_lib/node_modules
      - ./target

volumes:
  - name: cache
    host:
      path: /tmp/cache
