apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gluk64/franklin:server
          imagePullPolicy: Always
          ports: 
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: franklin-secret
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      nodeSelector:
        doks.digitalocean.com/node-pool: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prover
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prover
  template:
    metadata:
      labels:
        app: prover
    spec:
      containers:
        - name: prover
          image: gluk64/franklin:prover
          imagePullPolicy: Always
          resources:
            requests:
              memory: "0.5Gi"
          envFrom:
          - secretRef:
              name: franklin-secret
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      terminationGracePeriodSeconds: 5
      nodeSelector:
        doks.digitalocean.com/node-pool: prover
