apiVersion: v1
kind: Service
metadata:
  name: ${FRANKLIN_ENV}-server
  labels:
    app: ${FRANKLIN_ENV}-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ${FRANKLIN_ENV}-server
---
apiVersion: v1
kind: Service
metadata:
  name: ${FRANKLIN_ENV}-nginx
  labels:
    app: ${FRANKLIN_ENV}-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ${FRANKLIN_ENV}-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${FRANKLIN_ENV}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${FRANKLIN_ENV}-nginx
  template:
    metadata:
      labels:
        app: ${FRANKLIN_ENV}-nginx
    spec:
      containers:
        - name: ${FRANKLIN_ENV}-nginx
          image: gluk64/franklin-nginx:${FRANKLIN_ENV}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        doks.digitalocean.com/node-pool: prover
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${FRANKLIN_ENV}-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ${FRANKLIN_ENV}-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${FRANKLIN_ENV}-server
    spec:
      containers:
        - name: server
          image: gluk64/franklin:server
          imagePullPolicy: Always
          ports: 
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: ${FRANKLIN_ENV}-secret
          env:
          - name: FRANKLIN_ENV
            value: "${FRANKLIN_ENV}"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      nodeSelector:
        doks.digitalocean.com/node-pool: prover
