FORMAT: 1A

# zkSync API v0.2

<!-- include(./groups/accounts.apib) -->
<!-- include(./groups/batches.apib) -->
<!-- include(./groups/blocks.apib) -->
<!-- include(./groups/config.apib) -->
<!-- include(./groups/fee.apib) -->
<!-- include(./groups/network-status.apib) -->
<!-- include(./groups/tokens.apib) -->
<!-- include(./groups/transactions.apib) -->

# Data Structures

<!-- include(./types/accounts.apib) -->
<!-- include(./types/batches.apib) -->
<!-- include(./types/blocks.apib) -->
<!-- include(./types/config.apib) -->
<!-- include(./types/fee.apib) -->
<!-- include(./types/network-status.apib) -->
<!-- include(./types/pagination.apib) -->
<!-- include(./types/receipt.apib) -->
<!-- include(./types/tokens.apib) -->
<!-- include(./types/transactions.apib) -->

## TxState (enum)
+ queued
+ committed
+ finalized
+ rejected

## BlockNumber (enum)
+ (number)
+ lastCommitted
+ lastFinalized

## Request
+ network: localhost (Network, required)
+ apiVersion: v02 (fixed, required)
+ resource: /api/v0.2/... (string, required)
+ args (object, required)
+ timestamp: `2021-05-31T14:17:24.112536900Z` (string, required)

## Error
+ errorType: errorType (string, required)
+ code: 0 (number, required)
+ message: message (string, required)
