# Group Batches

## api/v0.2/transactions/batches [/transactions/batches]

### Submit batch of transactions [POST]
Submit batch of transactions.

+ Request (application/json)
    + Attributes
        + txs (array[TxWithSignature], required)
        + signature (BatchSignature, optional)

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (SubmitBatchResponse, required{{isResultNullable}})
        + error (Error, required, nullable)


## api/v0.2/transactions/batches/:txBatchHash [/transactions/batches/{txBatchHash}]

+ Parameters
    + txBatchHash (required, string, `{{txBatchHash}}`) ... The hash of the contents of the batch queried

### Get transactions batch status [GET]
Get transactions batch status (latest receipt)

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (BatchStatus, required{{isResultNullable}})
        + error (Error, required, nullable)
