# Group Tokens

## api/v0.2/tokens [/tokens{?from,limit,direction}]

+ Parameters
    + from (required, "latest" | number, `latest`) ... Token ID of transaction from which to show or `latest`
    + limit (required, number, `2`) ... The limit of tokens to be returned
    + direction (required, "newer" | "older", `older`) ... Newer or older than the ID of the `from`

### Get list of supported tokens [GET]
Returns the tokens that are currently supported by zkSync

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (object, required{{isResultNullable}})
            + pagination (PaginationFromNumber, required)
            + list (array[Token.Token], required)
        + error (Error, required, nullable)

## api/v0.2/tokens/:tokenLike [/tokens/{tokenLike}]

+ Parameters
    + tokenLike (required, string, `2`) ... ID, address or symbol of the token in the zkSync network

### Get token info [GET]
Get token into

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (Token.Token, required{{isResultNullable}})
        + error (Error, required, nullable)

## api/v0.2/tokens/:tokenLike/priceIn/:currency [/tokens/{tokenLike}/priceIn/{currency}]

+ Parameters
    + tokenLike (required, string, `2`) ... ID, address or symbol of the token in the zkSync network
    + currency (required, `usd` | number, `usd`) ... Either `usd` or ID of any of the supported tokens in the zkSync network

### Get token price [GET]
Get token price relative to another token

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (Token.Price, required{{isResultNullable}})
        + error (Error, required, nullable)

## api/v0.2/tokens/nft/:id [/tokens/nft/{id}]

+ Parameters
    + id (required, number, `{{nftId}}`) ... ID of the NFT in the zkSync network

### Get NFT info [GET]
Get NFT info

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (Token.NFTInfo, required{{isResultNullable}})
        + error (Error, required, nullable)

## api/v0.2/tokens/nft/:id/owner [/tokens/nft/{id}/owner]

+ Parameters
    + id (required, number, `{{nftId}}`) ... ID of the NFT in the zkSync network

### Get NFT owner ID [GET]
Get NFT owner ID

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (number, required{{isResultNullable}})
        + error (Error, required, nullable)

## api/v0.2/tokens/nft_id_by_tx_hash/:tx_hash [/tokens/nft_id_by_tx_hash/{tx_hash}]

+ Parameters
    + tx_hash (required, string, `{{mintNFTTxHash}}`) ... The hash of the MintNFT transaction

### Get NFT ID by the MintNFT transaction hash [GET]
Get NFT ID by the MintNFT transaction hash

+ Response 200 (application/json)
    + Attributes
        + request (Request, required)
        + status: success (string, required)
        + result (number, required{{isResultNullable}})
        + error (Error, required, nullable)
