## Account (object)
+ accountId: 12 (number, required)
+ address: `0xc0f97CC918C9d6fA4E9fc6be61a6a06589D199b3` (string, required)
+ nonce: 6412 (number, required)
+ pubKeyHash: `sync:82b9eb68c6f7f80cecf49ee1a20acb8ae9ecd602` (string, required)
+ lastUpdateInBlock: 15001 (number, required)
+ balances (object, required)
+ accountType (Account.Type, required, nullable)
+ nfts (Account.Balances, required)
+ mintedNfts (Account.Nfts, required)

## Account.Type (enum)
- Owned
- CREATE2

## Account.FullInfo (object)
+ depositing (Depositing, required)
+ committed (Account, required, nullable)
+ finalized (Account, required, nullable)

## Depositing (object)
+ balances (DepositingBalances, required)

## DepositingBalances (object)
+ *ETH* (DepositingFunds, required)

## DepositingFunds (object)
+ amount: `1000000000000000000` (string, required)
+ expectedAcceptBlock: 25136211 (number, required)

## Account.Balances (object)
+ *ETH*: `1000000000000000000` (string, required)

## Account.Nfts (object)
+ *100000* (Token.NFT, required)
