## Config (object)
+ network: `mainnet` (Network, required)
+ contract: `0x5D8cec831732d6DA03677a33430796C4840728f7` (string, required)
+ govContract: `0x70e7fB5A89f9556F8fF9611bB6f42C8eAFDB6c93` (string, required)
+ depositConfirmations: 10 (number, required)
+ zksyncVersion: `contractV4` (string, required)
