## PaginationFromHash (object)
+ from: `0x2dcb7cb4288b84766a1bef4a1bd4ae9ac15ab817f06ad07efc4dac035bcfdb45` (string, required)
+ limit: 2 (number, required)
+ direction: `older` (string, required)
+ count: 268 (number, required)

## PaginationFromNumber (object)
+ from: 5 (number, required)
+ limit: 2 (number, required)
+ direction: `older` (string, required)
+ count: 268 (number, required)
