## Network (enum)
+ mainnet
+ rinkeby
+ ropsten
+ localhost

## NetworkStatus (object)
- lastCommitted: 1298 (number, required)
- finalized: 1296 (number, required)
- totalTransactions: 1200000 (number, required)
- mempoolSize: 123 (number, required)
