## Token.Token (object)
- id: 12 (number, required)
- address: `0x0849D6ae02349352258Ca59c27bC6D3159A7b752` (string, required)
- symbol: `MLTT` (string, required)
- decimals: 18 (number, required)
- enabledForFees: true (boolean, required)

## Token.TokenLike (enum)
+ (number)
+ (string)

## Token.Price (object)
- tokenId: 12 (number, required)
- tokenSymbol: `MLTT` (string, required)
- priceIn: `USD` (string, required)
- decimals: 18 (number, required)
- price: `1.01` (string, required)

## Token.NFT (object)
- id: 100000 (number, required)
- contentHash: `0x2216aae3714e46a9efe0066ff5f3684c95ea9a680a4c39cd36e62b117cb1837c` (string, required)
- creatorId: 5 (number, required)
- creatorAddress: `0x1849D6ae02349352258Ca59c27bC6D3159A7b752` (string, required)
- serialId: 57 (number, required)
- address: `0x2DEEA6ae02349352258C2DEEA6bC6D31592DEEA6` (string, required)
- symbol: `NFT-100000`

## Token.NFTInfo (object)
- id: 100000 (number, required)
- contentHash: `0x2216aae3714e46a9efe0066ff5f3684c95ea9a680a4c39cd36e62b117cb1837c` (string, required)
- creatorId: 5 (number, required)
- creatorAddress: `0x1849D6ae02349352258Ca59c27bC6D3159A7b752` (string, required)
- serialId: 57 (number, required)
- address: `0x2DEEA6ae02349352258C2DEEA6bC6D31592DEEA6` (string, required)
- symbol: `NFT-100000`
- currentFactory: `0x5DFEA6ae02349352258C2DEEA6bC6D31592D5DFE` (string, required)
- withdrawnFactory: `0x5DFEA6ae02349352258C2DEEA6bC6D31592D5DFE` (string, required, nullable)
