## Transaction.InBlock (object)
- txHash: 0x732D0a2598ba5E9db4e5cfF36F86dF8dA88A959A (string, required)
- blockNumber: 12 (number, required)
- op (Transaction, required)
- status: rejected (TxState, required)
- failReason: Nonce mismatch (string, required, nullable)
- createdAt: `2018-12-12T01:02:03.123456789` (string, required, nullable)
- batchId: 155 (number, required, nullable)

## Transaction.Signed (object)
- tx (Transaction.InBlock, required)
- ethSignature: 0xb71ef30467c91b779ccc07c6615ac5fcd2e8293847dda0a6d0c63c85e95120c812e3f1e1973fc79f1718f45554120ffeca99b21b6d424dca854e8191415d2ce91b (string, required, nullable)

## Transaction.InBlock.L1 (object)
- txHash: 0x732D0a2598ba5E9db4e5cfF36F86dF8dA88A959A (string, required)
- blockNumber: 12 (number, required)
- op (Transaction.L1, required)
- status: rejected (TxState, required)
- failReason: Nonce mismatch (string, required, nullable)
- createdAt: `2018-12-12T01:02:03.123456789` (string, required, nullable)

## Transaction.L2.Transfer (object)
- type: Transfer (string, fixed)
- to: 0xD3c62D2F7b6d4A63577F2415E55A6Aa6E1DbB9CA (string, required)
- fee: 12000000000000000000 (string, required)
- from: {{address}} (string, required)
- nonce: 12123 (number, required)
- token: 0 (number, required)
- amount: 17500000000000000 (string, required)
- accountId: {{accountId}} (number, required)
- validFrom: 0 (number, required, nullable)
- validUntil: 1239213821 (number, required, nullable)
- signature (L2Signature, required)

## Transaction.L2.Withdraw (object)
- type: Withdraw (string, fixed)
- to: 0xD3c62D2F7b6d4A63577F2415E55A6Aa6E1DbB9CA (string, required)
- fee: 1200000000 (number, required)
- from: 0xD3c62D2F7b6d4A63577F2415E55A6Aa6E1DbB9CA (string, required)
- nonce: 12123 (number, required)
- tokenId: 10 (number, required)
- amount: 17500000000000000 (number, required)
- accountId: 12123 (number, required)
- validFrom: 0 (number, required, nullable)
- validUntil: 1239213821 (number, required, nullable)
- fast: false (boolean, required)
- signature (L2Signature, required)

## Transaction.L2.WithdrawWithEthHash (object)
- type: Withdraw (string, fixed)
- to: 0xD3c62D2F7b6d4A63577F2415E55A6Aa6E1DbB9CA (string, required)
- fee: 1200000000 (number, required)
- from: 0xD3c62D2F7b6d4A63577F2415E55A6Aa6E1DbB9CA (string, required)
- nonce: 12123 (number, required)
- tokenId: 10 (number, required)
- amount: 17500000000000000 (number, required)
- accountId: 12123 (number, required)
- validFrom: 0 (number, required, nullable)
- validUntil: 1239213821 (number, required, nullable)
- fast: false (boolean, required)
- signature (L2Signature, required)
- ethTxHash: 0xdda1287002282e1804af40a7c7373bd77cc99a2a27c88bf7908be45398e93148 (string, required, nullable)

## Transaction.L2.ChangePubKey (object)
- type: ChangePubKey (string, fixed)
- accountId: 1201 (number, required)
- account: 0x3EEe181F789c6585B39904eBAeAb10ACf70f5F1a (string, required)
- newPkHash: 5fcf0bad911e8fdebd4fd79b0a832bc92a694e55 (string, required)
- feeTokenId: 6 (number, required)
- fee: 121000000000000 (number, required)
- nonce: 51 (number, required)
- ethAuthData: *ECDSAAuthType* (AuthType, optional)
- signature (L2Signature, required)
- ethSignature: 0xf0947f0a731ada6e09ca99d3aafb1469a3baaf602eab2f5661edd30d6386 (string, optional)
- validFrom: 0 (number, required, nullable)
- validUntil: 1239213821 (number, required, nullable)

## Transaction.L2.ForcedExit (object)
- type: `ForcedExit` (string, fixed)
- initiatorAccountId: 12 (number, required)
- target: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- nonce: 1001 (number, required)
- tokenId: 5 (number, required)
- fee: `12000000000` (string, required)
- validFrom: 0 (number, required)
- validUntil: 1239213821 (number, required)
- signature (L2Signature, required)

## Transaction.L2.ForcedExitWithEthHash (object)
- type: `ForcedExit` (string, fixed)
- initiatorAccountId: 12 (number, required)
- target: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- nonce: 1001 (number, required)
- tokenId: 5 (number, required)
- fee: `12000000000` (string, required)
- validFrom: 0 (number, required)
- validUntil: 1239213821 (number, required)
- signature (L2Signature, required)
- ethTxHash: `0xdda1287002282e1804af40a7c7373bd77cc99a2a27c88bf7908be45398e93148` (string, required, nullable)

## Order (object)
- accountId: 12 (number, required)
- recipient: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- nonce: 1001 (number, required)
- tokenBuy: 1 (number, required)
- tokenSell: 2 (number, required)
- ratio: 100, 2 (array[string], required)
- amount: `100000000` (string, required)
- validFrom: 0 (number, required)
- validUntil: 1239213821 (number, required)
- signature (L2Signature, required)

## Transaction.L2.Swap (object)
- type: `Swap` (string, fixed)
- submitterId: 12 (number, required)
- submitterAddress: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- nonce: 1001 (number, required)
- orders (array[Order], required)
- amounts: 100000000, 20000 (array[string], required)
- fee: `12000000000` (string, required)
- feeToken: 5 (number, required)
- signature (L2Signature, required)

## Transaction.L2.MintNFT (object)
- type: `MintNFT` (string, fixed)
- creatorId: 12 (number, required)
- creatorAddress: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- contentHash: 0x2216aae3714e46a9efe0066ff5f3684c95ea9a680a4c39cd36e62b117cb1837c (string, required)
- recipient: 0x44de1b4a24548d6ff66fa8e56448d9de09955b00 (string, required)
- fee: `12000000000` (string, required)
- feeToken: 5 (number, required)
- nonce: 1001 (number, required)
- signature (L2Signature, required)

## Transaction.L2.WithdrawNFT (object)
- type: `WithdrawNFT` (string, fixed)
- accountId: 12 (number, required)
- from: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- to: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- token: 100000 (number, required)
- feeToken: 5 (number, required)
- fee: `12000000000` (string, required)
- nonce: 1001 (number, required)
- signature (L2Signature, required)
- fast: false (boolean, required)
- validFrom: 0 (number, required)
- validUntil: 1239213821 (number, required)

## Transaction.L2.WithdrawNFTWithEthHash (object)
- type: `WithdrawNFT` (string, fixed)
- accountId: 12 (number, required)
- from: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- to: 0x38de1b4a24548d6ff66fa8e56448d9de09955b08 (string, required)
- token: 100000 (number, required)
- feeToken: 5 (number, required)
- fee: `12000000000` (string, required)
- nonce: 1001 (number, required)
- signature (L2Signature, required)
- fast: false (boolean, required)
- validFrom: 0 (number, required)
- validUntil: 1239213821 (number, required)
- ethTxHash: `0xdda1287002282e1804af40a7c7373bd77cc99a2a27c88bf7908be45398e93148` (string, required, nullable)

## Transaction.Incoming (enum)
- (Transaction.L2.Transfer)
- (Transaction.L2.Withdraw)
- (Transaction.L2.ChangePubKey)
- (Transaction.L2.ForcedExit)
- (Transaction.L2.Swap)
- (Transaction.L2.MintNFT)
- (Transaction.L2.WithdrawNFT)

## Transaction.L2 (enum)
- (Transaction.L2.Transfer)
- (Transaction.L2.WithdrawWithEthHash)
- (Transaction.L2.ChangePubKey)
- (Transaction.L2.ForcedExitWithEthHash)
- (Transaction.L2.Swap)
- (Transaction.L2.MintNFT)
- (Transaction.L2.WithdrawNFTWithEthHash)

## Transaction.L1.Deposit
- type: `Deposit` (string, fixed)
- from: `0x555968cfc291aece5550822feb712d1cf66c57b4` (string, required)
- tokenId: 12 (number, required)
- amount: `18000000000000000` (string, required)
- to: `0x3f0d95988eb8538c74e609cac0c1ce56ff3d3179` (string, required)
- accountId: 1413 (number, required, nullable)
- ethHash: `0xdda1287002282e1804af40a7c7373bd77cc99a2a27c88bf7908be45398e93148` (string, required)
- id: 17002 (number, required)
- txHash: `0x2dcb7cb4288b847d8a1bef4a1bd4ae9ac15ab817f06ad07efc4dac035bcfdb45` (string, required)

## Transaction.L1.FullExit
- type: `FullExit` (string, fixed)
- accountId: 123 (number, required)
- tokenId: 34 (number, required)
- ethHash: `0x1216aae3714e46a9efe0066ff5f3684c95ea9a680a4c39cd36e62b117cb1837c` (string, required)
- id: 1348 (number, required)
- txHash: `0xaf0612970ea1b7809886ab0cce398bb14524d700e4c7305c54c34b5f9f3e6f56` (string, required)

## Transaction.L1 (enum)
- (Transaction.L1.Deposit)
- (Transaction.L1.FullExit)

## Transaction (enum)
- (Transaction.L2.Transfer)
- (Transaction.L2.WithdrawWithEthHash)
- (Transaction.L2.ChangePubKey)
- (Transaction.L2.ForcedExitWithEthHash)
- (Transaction.L2.Swap)
- (Transaction.L2.MintNFT)
- (Transaction.L2.WithdrawNFT)
- (Transaction.L1.Deposit)
- (Transaction.L1.FullExit)

## L2Signature (object)
- pubKey: {{pubKey}} (string, required)
- signature: {{l2Signature}} (string, required)

## ECDSAAuthType (object)
- type: `ECDSA` (string, fixed)
- batchHash: `0xcf70011f7220e08cd58493bf04be43addb4aaf4ec6a4e05b50bbe05aa066d` (string, required)

## OnchainAuthType (object)
- type: `Onchain` (string, fixed)

## CREATE2AuthType (object)
- creatorAddress: `0xCd4eA9f4346b992e906a3672a2Ce6632760efb10` (string, required)
- saltArg: `0x81d79d8c78a01373a37cd2d0b5d109798f5c7a07c3bf20b4d5` (string, required)
- codeHash: `0x896a58a92659223a74dd447ee259607d3bac01f9b826dfce62293b8861f4e729` (string, required)

## AuthType (enum)
- (ECDSAAuthType)
- (OnchainAuthType) 
- (CREATE2AuthType)

## EthereumSignature (object)
- type: `EthereumSignature` (string, fixed)
- signature: `{{ethereumSignature}}` (string, required)

## EIP1271Signature (object)
- type: `EIP1271Signature` (string, fixed)
- signature: `0xc9eb71b736ef69192d90a6516c5d66af883f6bc9a1749ed98edff106bcd49594618644860be89b08725de834d3a312d409810ecb39e9e7a5a5a9d8d870b166ab1c` (string, required)

## TxEthSignature (enum)
- (EthereumSignature)
- (EIP1271Signature)

## TxEthSignatureVariant (enum)
- (TxEthSignature)
- (array[TxEthSignature])

## TxWithSignature (object)
- tx (Transaction.Incoming, required)
- signature (TxEthSignatureVariant, required)

## Toggle2FAEthereumSignature
- type: `EthereumSignature` (string, fixed)
- signature: `{{toggle2FASignature}}` (string, required)

## Toggle2FAEthSignature (enum)
- (Toggle2FAEthereumSignature)
- (EIP1271Signature)

## Toggle2FAResult (object)
- success: true (boolean, required)
