[package]
name = "zksync_forced_exit_requests"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }

zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "1.0" }

zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_eth_signer = { path = "../../lib/eth_signer", version = "1.0" }
zksync_test_account = { path = "../../tests/test_account", version = "1.0" }

vlog = { path = "../../lib/vlog", version = "1.0" }

zksync_core = { path = "../zksync_core", version = "1.0" }
zksync_api = { path = "../zksync_api", version = "1.0" }
actix-web = "3.0.0"
ethabi = "12.0.0"
web3 = "0.13.0"
log = "0.4"
hex = "0.4"
metrics = "0.13.0-alpha.8"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }

tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
async-trait = "0.1"

num = { version = "0.3.1", features = ["serde"] }
