apiVersion: v1
kind: Endpoints
metadata:
  name: geth
subsets:
- addresses:
  - ip: 192.168.99.1
  ports:
  - port: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8545
    targetPort: 8545
