apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  labels:
    service: postgres
subsets:
- addresses:
    - ip: 192.168.99.1
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
