apiVersion: v1
kind: Service
metadata:
  name: dev-server
  labels:
    app: dev-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31108
    protocol: TCP
    name: http
  selector:
    app: dev-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-server
  labels:
    app: dev-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: dev-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-server
    spec:
      containers:
        - name: server
          image: matterlabs/server:latest
          imagePullPolicy: Never
          ports: 
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: dev-secret
          env:
          - name: CONTRACT_ADDR
            value: ""
          - name: GOVERNANCE_ADDR
            value: ""
          - name: PRIORITY_QUEUE_ADDR
            value: ""
          - name: BIND_TO
            value: "0.0.0.0"
          - name: PORT
            value: "3000"
          - name: WEB3_URL
            value: "http://geth:8545"
          - name: DATABASE_URL
            value: "postgres://postgres@postgres/plasma"
          - name: DB_POOL_SIZE
            value: "10"
          - name: OPERATOR_FRANKLIN_ADDRESS
            value: "0x241d9d2eebabfe5c07ea537f9c95ba3dd7fe8707"
          - name: CHAIN_ID
            value: "9"
          - name: GAS_PRICE_FACTOR
            value: "1"
          - name: TX_BATCH_SIZE
            value: "50"
          - name: MAX_OUTSTANDING_TXS
            value: "120000"
          - name: OPERATOR_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: franklin-secret
                key: OPERATOR_PRIVATE_KEY
          - name: OPERATOR_ETH_ADDRESS
            valueFrom:
              secretKeyRef:
                name: franklin-secret
                key: OPERATOR_ETH_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: dev-nginx
  labels:
    app: dev-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dev-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nginx
  labels:
    app: dev-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-nginx
  template:
    metadata:
      labels:
        app: dev-nginx
    spec:
      containers:
        - name: dev-nginx
          image: matterlabs/nginx:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
