/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { DummyTarget } from "./DummyTarget";

export class DummyTargetFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DummyTarget {
    return new Contract(address, _abi, signerOrProvider) as DummyTarget;
  }
}

const _abi = [
  {
    inputs: [],
    name: "get_DUMMY_INDEX",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initializationParameters",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "upgradeParameters",
        type: "bytes",
      },
    ],
    name: "upgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "verifyPriorityOperation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
