/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface OperationsInterface extends ethers.utils.Interface {
  functions: {
    "PACKED_DEPOSIT_PUBDATA_BYTES()": FunctionFragment;
    "PACKED_FULL_EXIT_PUBDATA_BYTES()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "PACKED_DEPOSIT_PUBDATA_BYTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PACKED_FULL_EXIT_PUBDATA_BYTES",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PACKED_DEPOSIT_PUBDATA_BYTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PACKED_FULL_EXIT_PUBDATA_BYTES",
    data: BytesLike
  ): Result;

  events: {};
}

export class Operations extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: OperationsInterface;

  functions: {
    PACKED_DEPOSIT_PUBDATA_BYTES(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "PACKED_DEPOSIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    PACKED_FULL_EXIT_PUBDATA_BYTES(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "PACKED_FULL_EXIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  PACKED_DEPOSIT_PUBDATA_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

  "PACKED_DEPOSIT_PUBDATA_BYTES()"(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  PACKED_FULL_EXIT_PUBDATA_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

  "PACKED_FULL_EXIT_PUBDATA_BYTES()"(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    PACKED_DEPOSIT_PUBDATA_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

    "PACKED_DEPOSIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PACKED_FULL_EXIT_PUBDATA_BYTES(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "PACKED_FULL_EXIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    PACKED_DEPOSIT_PUBDATA_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

    "PACKED_DEPOSIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PACKED_FULL_EXIT_PUBDATA_BYTES(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "PACKED_FULL_EXIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PACKED_DEPOSIT_PUBDATA_BYTES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "PACKED_DEPOSIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PACKED_FULL_EXIT_PUBDATA_BYTES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "PACKED_FULL_EXIT_PUBDATA_BYTES()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
