/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Operations } from "./Operations";

export class OperationsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Operations> {
    return super.deploy(overrides || {}) as Promise<Operations>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Operations {
    return super.attach(address) as Operations;
  }
  connect(signer: Signer): OperationsFactory {
    return super.connect(signer) as OperationsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Operations {
    return new Contract(address, _abi, signerOrProvider) as Operations;
  }
}

const _abi = [
  {
    inputs: [],
    name: "PACKED_DEPOSIT_PUBDATA_BYTES",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PACKED_FULL_EXIT_PUBDATA_BYTES",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6095610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c8063466dc2171460425780635ebcfa95146042575b600080fd5b6048605a565b60408051918252519081900360200190f35b602a8156fea2646970667358221220df463b8d36dad5cfd85e42e069a37fce6d9e7a56edaf52e29baa228fa10095dd64736f6c63430007030033";
