/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface OwnableInterface extends ethers.utils.Interface {
  functions: {
    "getMaster()": FunctionFragment;
    "transferMastership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getMaster", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferMastership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "getMaster", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferMastership",
    data: BytesLike
  ): Result;

  events: {};
}

export class Ownable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: OwnableInterface;

  functions: {
    getMaster(
      overrides?: CallOverrides
    ): Promise<{
      master: string;
      0: string;
    }>;

    "getMaster()"(
      overrides?: CallOverrides
    ): Promise<{
      master: string;
      0: string;
    }>;

    transferMastership(
      _newMaster: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferMastership(address)"(
      _newMaster: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getMaster(overrides?: CallOverrides): Promise<string>;

  "getMaster()"(overrides?: CallOverrides): Promise<string>;

  transferMastership(
    _newMaster: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferMastership(address)"(
    _newMaster: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getMaster(overrides?: CallOverrides): Promise<string>;

    "getMaster()"(overrides?: CallOverrides): Promise<string>;

    transferMastership(
      _newMaster: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferMastership(address)"(
      _newMaster: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getMaster(overrides?: CallOverrides): Promise<BigNumber>;

    "getMaster()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferMastership(
      _newMaster: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferMastership(address)"(
      _newMaster: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMaster(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMaster()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferMastership(
      _newMaster: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferMastership(address)"(
      _newMaster: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
