/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UpgradeableInterface extends ethers.utils.Interface {
  functions: {
    "upgradeTarget(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "upgradeTarget",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "upgradeTarget",
    data: BytesLike
  ): Result;

  events: {};
}

export class Upgradeable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UpgradeableInterface;

  functions: {
    upgradeTarget(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeTarget(address,bytes)"(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  upgradeTarget(
    newTarget: string,
    newTargetInitializationParameters: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeTarget(address,bytes)"(
    newTarget: string,
    newTargetInitializationParameters: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    upgradeTarget(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeTarget(address,bytes)"(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    upgradeTarget(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgradeTarget(address,bytes)"(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    upgradeTarget(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeTarget(address,bytes)"(
      newTarget: string,
      newTargetInitializationParameters: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
