
## Token.Token (object)
- `id`: 12 (number, required)
- `address`: `0x0849D6ae02349352258Ca59c27bC6D3159A7b752` (string, required)
- `symbol`: `MLTT` (string, required)
- `decimals`: 18 (number, required)
- `enabledForFees`: true (boolean, required)

## Token.TokenLike (enum)
+ (number)
+ (string)

## Token.Price (object)
- `tokenId`: 12 (number, required)
- `tokenSymbol`: `MLTT` (string, required)
- `priceIn`: `USD` (string, required)
- `decimals`: 18 (number, required)
- `price`: `1.01` (string, required)
