[package]
name = "zksync_witness_generator"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_state = { path = "../../lib/state", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }
zksync_circuit = { path = "../../lib/circuit", version = "1.0" }

zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_prover_utils = { path = "../../lib/prover_utils", version = "1.0" }
zksync_prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }

vlog = { path = "../../lib/vlog", version = "1.0" , features=['actix']}
tracing = "0.1.22"

serde = "1.0.90"
serde_json = "1.0.0"
metrics = "=0.13.0-alpha.8"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
actix-rt = "1.1.1"
actix-web = "3.0.0"
actix-web-httpauth = "0.5.0"

ctrlc = { version = "3.1", features = ["termination"] }
jsonwebtoken = "7"
anyhow = "1.0"
async-trait = "0.1.42"

[dev-dependencies]
zksync_prover = { path = "../prover", version = "1.0" }
num = { version = "0.3.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.10", features = ["blocking"] }
