name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      run: |
        export PATH="`pwd`/bin:$PATH"
        export FRANKLIN_HOME=`pwd`
        yarn cache clean
        franklin yarn || true
        franklin build-contracts
        cargo check
