name: publish zk-environment docker image

on:
  pull_request:
    branches:
      - dev
    types: [closed]
    paths:
      - 'docker/zk-environment/Dockerfile'
      - '.github/workflows/zk-environment.publish.yml'
  workflow_dispatch:
    branches:
      - 'dev'

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Push Docker image to Docker Hub
    runs-on: [matterlabs-ci-runner]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: "matterlabs/zk-environment:latest"
          file: docker/zk-environment/Dockerfile
          no-cache: true
